spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woniu?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  elasticsearch:
    rest:
      uris: http://192.168.232.168:9200
mybatis:
  mapper-locations: /mappers/*.xml